### ISSUE TITLE
stuck at Unpacking boot image

### ISSUE THREAD

**Issue by lattice0** [daboynb/magisk_for_linux#1]
``` 
/bin/bash ./boot_patch.sh /home/dev/project/android_hacking_container/devices/../../poco_m3/rom/r/boot.img
Unpacking boot image
+ ./magiskboot unpack /home/dev/project/android_hacking_container/devices/../../poco_m3/rom/r/boot.img
```

then it gets stuck forever

**Comment by daboynb** [comment]
Hi,
this sounds to me like a magisk issue, not a script "bug". Searching on xda I've found a lot of people that got stuck on that point, some of them had resolved by using the canary version of magisk. I've changed the script to download and unzip that version. "https://github.com/daboynb/magisk_for_linux/blob/main/magisk_canary.sh".  I hope this will fix your problem.

**Comment by lattice0** [comment]
Looks like it was fixed in the new magisk. But I inspected the extracted `magiskboot` and there was a message saying that a bug in the unzipper happened. Maybe it happens becausa of randomness and thus on some magisk releases it wont happen

**Comment by lattice0** [comment]
It started giving the error again in v25.0. I think it's a bug in `unzip`, take a look at `magiskboot` in binary

![image](https://user-images.githubusercontent.com/6632321/172958420-0307605f-2589-4778-974a-66d2fc8be313.png)

**Comment by daboynb** [comment]
Today I will run it to make some tests and will try to solve this issue.
I've run it on ubuntu 20.04 and debian 9 without errors last time.

**Comment by daboynb** [comment]
Tested now on:
- ubuntu 22.04 fresh install
- version of unzip Installed: 6.0-26ubuntu3

`- Unpacking boot image
Parsing boot image: [/home/myuser/Downloads/boot.img]
HEADER_VER      [2]
KERNEL_SZ       [41820172]
RAMDISK_SZ      [1309807]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
DTB_SZ          [1566663]
OS_VERSION      [11.0.0]
OS_PATCH_LEVEL  [2021-08]
PAGESIZE        [4096]
NAME            []
CMDLINE         [androidboot.hardware=qcom androidboot.console=ttyMSM0 androidboot.memcg=1 lpm_levels.sleep_disabled=1 video=vfb:640x400,bpp=32,memsize=3072000 msm_rtb.filter=0x237 service_locator.enable=1 androidboot.usbcontroller=a600000.dwc3 swiotlb=2048 loop.max_part=7 cgroup.memory=nokmem,nosocket reboot=panic_warm buildvariant=user]
CHECKSUM        [bf0de180a09e44c282683c62ce8f7acbfe016334000000000000000000000000]
KERNEL_FMT      [raw]
RAMDISK_FMT     [gzip]
VBMETA
- Checking ramdisk status
Loading cpio: [ramdisk.cpio]
- Stock boot image detected
- Patching ramdisk
Loading cpio: [ramdisk.cpio]
Add entry [init] (0750)
Create directory [overlay.d] (0750)
Create directory [overlay.d/sbin] (0750)
Add entry [overlay.d/sbin/magisk32.xz] (0644)
Add entry [overlay.d/sbin/magisk64.xz] (0644)
Patch with flag KEEPVERITY=[false] KEEPFORCEENCRYPT=[false]
Found fstab file [fstab.qcom]
Remove pattern [,avb=vbmeta_system]
Remove pattern [,avb_keys=/avb/q-gsi.avbpubkey:/avb/r-gsi.avbpubkey:/avb/s-gsi.avbpubkey]
Remove pattern [,avb=vbmeta_system]
Remove pattern [,avb=vbmeta_system]
Remove pattern [,avb]
Remove pattern [,avb]
Remove pattern [,fileencryption=aes-256-xts:aes-256-cts:v2+inlinecrypt_optimized+wrappedkey_v0]
Loading cpio: [ramdisk.cpio.orig]
Backup mismatch entry: [fstab.qcom] -> [.backup/fstab.qcom]
Backup mismatch entry: [init] -> [.backup/init]
Record new entry: [overlay.d] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/magisk32.xz] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/magisk64.xz] -> [.backup/.rmlist]
Create directory [.backup] (0000)
Add entry [.backup/.magisk] (0000)
Dump cpio: [ramdisk.cpio]
Loading dtbs from [dtb]
Remove pattern [,avb]
Remove pattern [,avb]
- Patch fstab in dtb
Patch @ 0228DD7C [736B69705F696E697472616D667300] -> [77616E745F696E697472616D667300]
- Repacking boot image
Parsing boot image: [/home/myuser/Downloads/boot.img]
HEADER_VER      [2]
KERNEL_SZ       [41820172]
RAMDISK_SZ      [1309807]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
DTB_SZ          [1566663]
OS_VERSION      [11.0.0]
OS_PATCH_LEVEL  [2021-08]
PAGESIZE        [4096]
NAME            []
CMDLINE         [androidboot.hardware=qcom androidboot.console=ttyMSM0 androidboot.memcg=1 lpm_levels.sleep_disabled=1 video=vfb:640x400,bpp=32,memsize=3072000 msm_rtb.filter=0x237 service_locator.enable=1 androidboot.usbcontroller=a600000.dwc3 swiotlb=2048 loop.max_part=7 cgroup.memory=nokmem,nosocket reboot=panic_warm buildvariant=user]
CHECKSUM        [bf0de180a09e44c282683c62ce8f7acbfe016334000000000000000000000000]
KERNEL_FMT      [raw]
RAMDISK_FMT     [gzip]
VBMETA
Repack to boot image: [new-boot.img]
HEADER_VER      [2]
KERNEL_SZ       [41820172]
RAMDISK_SZ      [1728168]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
DTB_SZ          [1566663]
OS_VERSION      [11.0.0]
OS_PATCH_LEVEL  [2021-08]
PAGESIZE        [4096]
NAME            []
CMDLINE         [androidboot.hardware=qcom androidboot.console=ttyMSM0 androidboot.memcg=1 lpm_levels.sleep_disabled=1 video=vfb:640x400,bpp=32,memsize=3072000 msm_rtb.filter=0x237 service_locator.enable=1 androidboot.usbcontroller=a600000.dwc3 swiotlb=2048 loop.max_part=7 cgroup.memory=nokmem,nosocket reboot=panic_warm buildvariant=user]
CHECKSUM        [18a284c7234354eebef1fa5751fa648fc3973f09000000000000000000000000]
`

It work here.

**Comment by lattice0** [comment]
Can you try to install multiple times? It looks like the unzip apk fails with some probability

-------- Mensagem Original --------
Ativo 10 de jun. de 2022 06:17, daboynb escreveu:

**Comment by daboynb** [comment]
Tried again, this time with magisk_canary,sh. Work flawless.

Tried with my boot.img, oneplus boot.img and xiaomi boot.img. All images got created without issues.

`- Unpacking boot image
Parsing boot image: [/home/myuser/Downloads/boot.img]
HEADER_VER      [0]
KERNEL_SZ       [15949258]
RAMDISK_SZ      [1352222]
SECOND_SZ       [0]
EXTRA_SZ        [0]
OS_VERSION      [12.0.0]
OS_PATCH_LEVEL  [2022-04]
PAGESIZE        [4096]
NAME            []
CMDLINE         [console=ttyMSM0,115200n8 earlycon=msm_geni_serial,0xA84000 androidboot.hardware=qcom androidboot.console=ttyMSM0 androidboot.usbcontroller=a600000.dwc3 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 msm_rtb.filter=0x237 service_locator.enable=1 swiotlb=2048 loop.max_part=7 androidboot.configfs=true buildvariant=userdebug]
CHECKSUM        [09fed0df9098ec7acce38524dbd9af83de679165000000000000000000000000]
KERNEL_DTB_SZ   [771298]
KERNEL_FMT      [gzip]
RAMDISK_FMT     [gzip]
VBMETA
- Checking ramdisk status
Loading cpio: [ramdisk.cpio]
- Stock boot image detected
- Patching ramdisk
Loading cpio: [ramdisk.cpio]
Add entry [init] (0750)
Create directory [overlay.d] (0750)
Create directory [overlay.d/sbin] (0750)
Add entry [overlay.d/sbin/magisk32.xz] (0644)
Add entry [overlay.d/sbin/magisk64.xz] (0644)
Patch with flag KEEPVERITY=[false] KEEPFORCEENCRYPT=[false]
Loading cpio: [ramdisk.cpio.orig]
Backup mismatch entry: [init] -> [.backup/init]
Record new entry: [overlay.d] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/magisk32.xz] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/magisk64.xz] -> [.backup/.rmlist]
Create directory [.backup] (0000)
Add entry [.backup/.magisk] (0000)
Dump cpio: [ramdisk.cpio]
Loading dtbs from [kernel_dtb]
Remove pattern [,avb]
Remove pattern [,avb]
- Patch fstab in kernel_dtb
Patch @ 0220F634 [736B69705F696E697472616D667300] -> [77616E745F696E697472616D667300]
- Repacking boot image
Parsing boot image: [/home/myuser/Downloads/boot.img]
HEADER_VER      [0]
KERNEL_SZ       [15949258]
RAMDISK_SZ      [1352222]
SECOND_SZ       [0]
EXTRA_SZ        [0]
OS_VERSION      [12.0.0]
OS_PATCH_LEVEL  [2022-04]
PAGESIZE        [4096]
NAME            []
CMDLINE         [console=ttyMSM0,115200n8 earlycon=msm_geni_serial,0xA84000 androidboot.hardware=qcom androidboot.console=ttyMSM0 androidboot.usbcontroller=a600000.dwc3 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 msm_rtb.filter=0x237 service_locator.enable=1 swiotlb=2048 loop.max_part=7 androidboot.configfs=true buildvariant=userdebug]
CHECKSUM        [09fed0df9098ec7acce38524dbd9af83de679165000000000000000000000000]
KERNEL_DTB_SZ   [771298]
KERNEL_FMT      [gzip]
RAMDISK_FMT     [gzip]
VBMETA
Repack to boot image: [new-boot.img]
HEADER_VER      [0]
KERNEL_SZ       [15949259]
RAMDISK_SZ      [1814544]
SECOND_SZ       [0]
EXTRA_SZ        [0]
OS_VERSION      [12.0.0]
OS_PATCH_LEVEL  [2022-04]
PAGESIZE        [4096]
NAME            []
CMDLINE         [console=ttyMSM0,115200n8 earlycon=msm_geni_serial,0xA84000 androidboot.hardware=qcom androidboot.console=ttyMSM0 androidboot.usbcontroller=a600000.dwc3 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 msm_rtb.filter=0x237 service_locator.enable=1 swiotlb=2048 loop.max_part=7 androidboot.configfs=true buildvariant=userdebug]
CHECKSUM        [4dbfe1b343b6e8a5d13416ceecde1f52573c60f2000000000000000000000000]
`

**Comment by lattice0** [comment]
Which OS you're using? Maybe unzip for my ubuntu 21.10 is buggy. What I can say is that sometimes it works, sometimes I get that bufgy magiskboot with text inside, that's why it gets stuck forever

-------- Mensagem Original --------
Ativo 10 de jun. de 2022 08:46, daboynb escreveu:

**Comment by daboynb** [comment]
Now I'm on ubuntu 22.04 64 bit fresh install. Tested on ubuntu 20.04 and debian 9 too (64 bit) . Yeah most probably your unzip is the problem. Wich version of unzip you have installed?

**Comment by lattice0** [comment]
```
unzip -v
UnZip 6.00 of 20 April 2009, by Debian. Original by Info-ZIP.

Latest sources and executables are at ftp://ftp.info-zip.org/pub/infozip/ ;
see ftp://ftp.info-zip.org/pub/infozip/UnZip.html for other sites.

Compiled with gcc 9.2.0 for Unix (Linux ELF).

UnZip special compilation options:
        ACORN_FTYPE_NFS
        COPYRIGHT_CLEAN (PKZIP 0.9x unreducing method not supported)
        SET_DIR_ATTRIB
        SYMLINKS (symbolic links supported, if RTL and file system permit)
        TIMESTAMP
        UNIXBACKUP
        USE_EF_UT_TIME
        USE_UNSHRINK (PKZIP/Zip 1.x unshrinking method supported)
        USE_DEFLATE64 (PKZIP 4.x Deflate64(tm) supported)
        UNICODE_SUPPORT [wide-chars, char coding: UTF-8] (handle UTF-8 paths)
        LARGE_FILE_SUPPORT (large files over 2 GiB supported)
        ZIP64_SUPPORT (archives using Zip64 for large files supported)
        USE_BZIP2 (PKZIP 4.6+, using bzip2 lib version 1.0.8, 13-Jul-2019)
        VMS_TEXT_CONV
        WILD_STOP_AT_DIR
        [decryption, version 2.11 of 05 Jan 2007]

UnZip and ZipInfo environment options:
           UNZIP:  [none]
        UNZIPOPT:  [none]
         ZIPINFO:  [none]
      ZIPINFOOPT:  [none]
```

**Comment by lattice0** [comment]
I have notified Julian Seward as noted in the bug message in my picture

**Comment by daboynb** [comment]
Well, thanks. 

Now I'm installing ubuntu 21.10 on a vm, to try to  reproduce the issue and find a solution.

Update: Tested on ubuntu 21.10 and all is working. Runned 6 times without any errors.

You can try installing the new unzip version https://github.com/daboynb/magisk_for_linux/raw/main/unzip_6.0-26_ubuntu_amd64.deb
and see if it solve the issue.
